name: build

on:
  push:
  pull_request:
jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 13
        xcode:
          - latest-stable
    runs-on: macos-${{ matrix.macos }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild -scheme "Chess" -sdk iphonesimulator -destination "name=iPhone 15" clean build
